package:
  name: hello-wolfi
  version: 0.1.0
  epoch: 0
  description: HTTP Hello wolfi Server
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle
      - busybox
      - go
  environment:
    CGO_ENABLED: "0"


pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cpanato/hello-wolfi
      tag: v${{package.version}}
      expected-commit: ad61c3e737f0d60b4acab98b3089da4e2d9b69b5

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      GOARCH=$(go env GOARCH) go build -o ${{targets.destdir}}/usr/bin/hello-wolfi

  - uses: strip
